### ISSUE TITLE
Compile Bug about Typescript version

### ISSUE THREAD

**Issue by CatREFuse** [PluginFinchy/Figma-Vue3-Template#4]
With default `package.json`, Compiling always fails like the image below
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/8400960/170461633-270436f2-1dbc-4234-b59f-b7d950c98c5e.png">

Changing Typescript version to 4.6.4 can solve it.

**Comment by LukeFinch** [comment]
Thanks, just updated.
